config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :restaurants, only: [:show, :index] do
    resources :reservations, only: [:show, :create, :edit, :destroy] 
  end

  resources :users, only: [:new, :create, :show, :edit]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant 
	belongs_to :user

	validate :availability

	private
	def availability # need to write a test for this aswell
		unless restaurant.available?(party_size, time)
			errors.add(:base, "No restaurant for you!")
		end
	end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reservations
	has_many :users, through: :reservations

	def available?(party_size, start_time)
    reserved = reservations.where(:time => start_time).sum(:party_size)
    party_size <= (capacity - reserved)
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reservations
	has_many :restaurants, through: :reservations
	
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end
  

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :load_restaurant

  before_filter :ensure_logged_in

  def show
  	@reservation = Reservation.find(params[:id])

    if current_user
    @reservation = @Restaurant.reviews.build
    end
  end

  def create
  	# @reservation = Reservation.new
      # @reservation.user = current_user
      # @restaurant = Restaurant.find(params[:restaurant_id])
      # @reservation = @restaurant.reservations.build(reservation_params)
      @reservation = Reservation.new(reservation_params)
      @reservation.user_id = current_user.id
      @reservation.restaurant_id = params[:restaurant_id]
  
  		if @reservation.save
  			redirect_to restaurants_path, notice: "Congratulations! We looks forward to seeing you =<(^o^<)"
  		else
  			render 'restaurants/show'
  		end
  end

  def edit
  	@reservation = Reservation.find(params[:id])
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
  end

  private
  def reservation_params
    params.require(:reservation).permit(:time, :party_size, :restaurant_id, :user_id, :name, :email, :request)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show 
    @restaurant = Restaurant.find(params[:id])

    if current_user
    @reservation = @restaurant.reservations.build
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new

    if @restaurant.save
      redirect_to restaurants_url
    else 
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :email, :capacity, :menu,)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to restaurants_url, notice: "(>^.^)>===WELCOME, #{user.name}==☆"
  	else
      flash.now[:alert] = "Invalid email or password"
      render :new
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to restaurants_url, notice: "Thank you, come again!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to restaurants_url, notice: "Account created"
  	else
  		render "new"
  	end
  end

  def show
    @user = User.find(params[:id])
  end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reservoir</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<header>

<a href="/restaurants">RESERVOIR</a>

</header>

<body>

	<p class="userinfo">
      <% if current_user %>
        Signed in as <%= link_to current_user.name, current_user %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Get started(〃￣ω￣〃ゞ)", new_user_path %>
      <% end %>
    </p>

	  <% if flash[:notice] %>
    	<p id="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
     	<p id="alert"><%= flash[:alert] %></p>
      <% end %>
	<div class="things">
	  <%= yield %>
    </div>

    <footer>&copy; Bitmaker Boizzz</footer>

</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> Unable to make reservation:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@reservation) do |f| %>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_field :time %>
  </div>
  <div class="field">
    <%= f.label :party_size %><br />
    <%= f.number_field :party_size %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :restaurant_id %>
  </div>
   <div class="field">
    <%= f.label :restaurant_id %><br />
    <%= f.number_field :restaurant_id %>
  </div>
   <div class="field">
    <%= f.label :email %><br />
    <%= f.email :email %>
  </div>
   <div class="field">
    <%= f.label :request %><br />
    <%= f.text_area :request %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/create.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/edit.html.erb
<h1>Edit Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/reservations/show.html.erb
<p> <%= @reservation.name %>, <%= @reservation.restaurant_id %>, <%= @reservation.time %>, <%= @reservation.party_size %></p>

<% if current_user #does this sync correctly?%> 

	<h3>Reservations</h3>

	<p>Reservations for <%= @reservation.name %></p>

	<% @reservation.restaurants.each do |restaurant| %>

		<p>
			<%= @reservation.time %>
			<br>
			<% if restaurant.user != nil %>
			<em> booked by <%= reservation.user.name %></em>
			Reservation date: <%= reservation.created_at #??? should this have been implemented in schema???%> 
			<% end %>
		</p>
	<% end %>
<% end %>

app/views/restaurants/_formreserve.html.erb
<% if current_user %>
<div class="make_res">
	<h1>Make a reservation!</h1>

	<%= form_for([@restaurant, @reservation]) do |f| %>
			<% if @reservation.errors.any? %>
				<div id="error_explanation">
					<h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved </h2> 
					<ul>
					<% @reservation.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
					</ul>
				</div>
			<% end %>
		<div class="reserve_form">
			<div class="field">
				<%= f.datetime_select :time, ampm: true, default: 1.days.from_now, discard_minute: true, class: "form_fields" %><br>
			</div>
			<div class="field">
				<%= f.number_field :party_size, placeholder: "Party size", class: "form_fields" %><br>
			</div>
			<div>
				<%= f.hidden_field :name, :value => @restaurant.name %>
			</div>
			<div class="actions">
				<%= f.submit class: "form_fields" %>
			</div>
		</div>
		<% end %>
	<% end %>
	<% unless current_user %>
	  <p>Please <%= link_to "log in", new_session_path %> to make a reservation.</p> 
	<% end %>
</div>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<h3>Restaurants</h3>

<!-- JAVASCRIPT MAGIC AGAIN FOR THE TOGGLING -->

<script type="text/javascript">
<!--
    function toggle_visibility(id) {
       var e = document.getElementById(id);
       if(e.style.display == 'block')
          e.style.display = 'none';
       else
          e.style.display = 'block';
    }
//-->
</script>

<!-- IS THERE A WAY TO DO THIS MORE ELEGANTLY -->
<!-- i have the same text on 2 pages :( this is sad -->
<div>
	<% @restaurants.each do |restaurant| %>
	<div id="<%=restaurant.name%>">
	  	<h4 class="restname"><strong><%= link_to restaurant.name, restaurant_path(restaurant) %></strong></h4>
	  	<ul>
	  		<li>Located @ <%= restaurant.location%></li>
		  	<li>Contact: <%= restaurant.email %></li>
		  	<li>Capacity: <%= restaurant.capacity %></li>
		  	<li><a href="#<%=restaurant.name%>" onclick="toggle_visibility('menu_<%=restaurant.name%>');">Click here to view the menu!</a>



			<div id="menu_<%=restaurant.name%>" style="display: none"><ul>
				<% restaurant.menu.split(", ").each do |item| %>
				<li><%= item %></li>
				<% end %>
				</ul>
				</div>
			</li>
	  	</ul>
	  	<p><%= link_to "View Restaurant",restaurant_path(restaurant) %></p>
	</div>
	<% end %>
</div>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>

app/views/restaurants/show.html.erb
<h1><strong><%= @restaurant.name %></strong></h1>

<!-- JAVASCRIPT MAGIC GOING ON HERE WHOAOAH -->

<script language="javascript"> 
function toggle() {
	var ele = document.getElementById("toggleText");
	var text = document.getElementById("displayText");
	if(ele.style.display == "block") {
    		ele.style.display = "none";
		text.innerHTML = "show";
  	}
	else {
		ele.style.display = "block";
		text.innerHTML = "hide";
	}
} 
</script>



<div>
	  	<ul>

	  		<li>Located @ <%= @restaurant.location%></li>
		  	<li>Contact: <%= @restaurant.email %></li>
		  	<li>Capacity: <%= @restaurant.capacity %></li>
		  	<li><a id="displayText" href="javascript:toggle();">Click here to view menu preview</a>
			<div id="toggleText" style="display: none"><ul>
				<% @restaurant.menu.split(", ").each do |item| %>
				<li><%= item %></li>
				<% end %>
				</ul>
				</div>
			</li>
	  	</ul>
	  <p><%= link_to "Back to Restaurants",restaurants_url%></p>
</div>

<%= render 'restaurants/formreserve', locals: { restaurant: @restaurant, reservation: @reservation } %>
	  	

app/views/users/new.html.erb
<h5>Please fill out the following details to create an account</h5>

<%= form_for @user do |u| %>
	<% if @user.errors.any? %>
	<!-- .any? returns true if @user.errors isn't emtpy -->
		<div class="error">
			<h2>Invalid form</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
		<div class="field">
			<%= u.label :name %><br />
			<%= u.text_field :name %>
		</div>
		<div class="field">
			<%= u.label :email %><br />
			<%= u.text_field :email %>
		</div>
		<div class="field">
			<%= u.label :password %><br />
			<%= u.text_field :password %>
		</div>
		<div class="field">
			<%= u.label :password_confirmation %><br />
			<%= u.text_field :password_confirmation %>
		</div>
		<div class="actions"><%= u.submit %> </div>
	<% end %>

app/views/users/show.html.erb
<h3><strong><%= @user.name %></strong></h3>

<p><%= @user.name %>, <%= @user.id %></p>
<p><%= @user.email %></p>

<h2>Reservations</h2>

<% @user.reservations.each do |reservation| %>
	<div>
		<p>Restaurant: <%= reservation.restaurant.name %></p>
		<p>Date: <%= reservation.time.strftime('%A, %d %b %Y @ %l:%M %p') %></p>
		<p>Party Size: <%= reservation.party_size %></p>
	</div>
	<div>
		<%= link_to "View Restaurant", restaurant_path(reservation.restaurant)  %>
	</div>
<% end %>

<%= link_to 'Back', :back %>